file_format: "1"
id: weact_mini_f411ce
name: WeAct Studio MiniF4 STM32F411CE
url: https://github.com/WeActStudio/WeActStudio.MiniSTM32F4x1
type: controller
tags:
  - usb
features:
  - usb
siblings:
  - weact_mini_f411ce@blackpill
variants:
  - variant: blackpill
    interconnects:
      - id: blackpill
